# Base our image on an official, minimal image of our preferred Ruby
FROM ruby:2.2.3

# Install essential Linux packages for development plus node.js
RUN echo "deb http://http.us.debian.org/debian jessie main" >> /etc/apt/sources.list && \
    apt-get update -qq && \
    apt-get install -y --force-yes --no-install-recommends git build-essential curl libpq-dev cmake gnupg pkg-config wget && \
    curl -sL https://deb.nodesource.com/setup_10.x | sh - && \
    apt-get install -y --force-yes --no-install-recommends nodejs

# openssh-client en primar apt-instal, antes de wget
